development:
  adapter: postgresql
  encoding: utf8
  database: chats_development
  username: gopikrishna
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: chats_test
  username: gopikrishna
  password:
  host: localhost